name: Update Index

on:
  push:
    branches:
      - master
    paths:
      - 'pavlenko.tech/content/posts/**.md'  # Запускать только когда изменяются markdown файлы в posts

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./pavlenko.tech
      
      - name: Run update-index script
        run: npm run update-index
        working-directory: ./pavlenko.tech
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pavlenko.tech/content/posts/index.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update index.json"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 